version: '3.8'

services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    command: npm run dev
    networks:
      - devlaunch-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/devlaunch
      - JWT_SECRET=devlaunch_jwt_secret_dev
      - CORS_ORIGIN=http://localhost:3000
      - SOLANA_RPC_URL=https://api.devnet.solana.com
    command: npm run dev
    depends_on:
      - mongodb
    networks:
      - devlaunch-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    command: mongod --logpath=/dev/null # Reduce log output
    networks:
      - devlaunch-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    networks:
      - devlaunch-network

volumes:
  mongodb-data:

networks:
  devlaunch-network:
    driver: bridge 